### ISSUE TITLE
你好老师！请问您的模型如何进行问题测试

### ISSUE THREAD

**Issue by ChuanMeng** [DouYishun/KB-QA#1]
您好老师，
      非常感谢您提供KB-QA的源码供大家学习，我是初学者，还有很多地方不太懂，我按照您在文中的指示进行了模型训练，但是训练完了如何做问答测试呢？谢谢您！

**Comment by Yishun99** [comment]
这是NLP的课程项目（尚需完善），没有单独写测试文件。
evaluation在train.py中。数据格式请参考data。

**Comment by yanqiangmiffy** [comment]
@DouYishun 你好，请问下， 现在基于目前训练完成的模型，是否自己可以写测试文件（问答测试，输入一个问题，给出答案）吗？

**Comment by Yishun99** [comment]
最好有相应的知识库

**Comment by yanqiangmiffy** [comment]
@DouYishun 好的谢谢

**Comment by HwJhx** [comment]
您好，有几个问题想请教下：
1.该项目中的word2vec是事先训练好的吗？ 如果是的话，我是否应该根据自己的语料重新训练一份？
   我的语料是 “疾病症状”->“建议用药”。是不是这两个都要一起训练？
2. 实体对齐和歧义消除有没有做？
3. knowledge_file、train_file这两者有什么关系吗？
4.您项目中biLSTM 是用于做什么的呢？

谢谢

**Comment by Yishun99** [comment]
@HwJhx 
1.word2vec是中文维基百科预训练的；个人认为不需要；可尝试
2.没有
3.knowledge是qa的领域知识。
4.https://colah.github.io/posts/2015-08-Understanding-LSTMs/

**Comment by HwJhx** [comment]
首先感谢您的回复！
1. 我理解train的过程中使用双向LSTM，是为了将问题和答案（正确的和错误的）进行向量化；最后从knowledge找到相似的正确答案；这样理解是否正确？
2. 另外预料中为何要出现3个错误答案呢？
3.双向LSTM一般都跟着softmax，那么这个项目中softmax是进行了怎样的分类？
谢谢！

**Comment by HwJhx** [comment]
首先感谢您的回复！

1. 我理解train的过程中使用双向LSTM，是为了将问题和答案（正确的和错误的）进行向量化；最后从 
    knowledge找到相似的正确答案；这样理解是否正确？
2. 另外语料中为何要出现3个错误答案呢？
3. 双向LSTM一般都跟着softmax，那么这个项目中softmax是进行了怎样的分类？
   谢谢

**Comment by Yishun99** [comment]
1.
2. 4选1
3. 没有做分类，做的是max-margin
