### ISSUE TITLE
词向量文件缺失

### ISSUE THREAD

**Issue by yanqiangmiffy** [DouYishun/KB-QA#4]
FileNotFoundError: [Errno 2] No such file or directory: '/home/douyishun/zhwiki_2017_03.sg_50d.word2vec'

你好请问下去哪里下载词向量文件，老师方便发邮箱到yanqiangmiffy@gmail.com吗，多谢了。或者应该去哪里找预料去训练

**Comment by Yishun99** [comment]
在另外一个issue
