### ISSUE TITLE
如何进行训练和测试

### ISSUE THREAD

**Issue by shuhaoxu** [DouYishun/KB-QA#7]
您好，我是刚刚接触问答系统和word2vec工具的，目前需要的库和环境已经搭建好了，但是在运行train.py时，发现有一个load预训练的模型，但是您提供的包里面没有.word2vec的文件，想问一下我需要如何做来得到这个预训练的嵌入文件。
十分感谢！

**Comment by Yishun99** [comment]
现在readme中可以找到了。
