### ISSUE TITLE
请问您的训练精确度是多少？训练用了多长时间（多少step）

### ISSUE THREAD

**Issue by HwJhx** [DouYishun/KB-QA#8]
您好！ 
我用您的训练数据进行训练（配置没有更改），目前还在运行中（10个小时左右），已经训练了1550个step,其中：

- train acc为0.72, 

- evaluation  acc:0.4355

请问:

- 您那边训练一共用了多少个step

- train acc 和 evaluation  acc 最终是多少？

**Comment by Yishun99** [comment]
结果相近，貌似出现了严重的过拟合=_=
我和别的同学结果类似，应该是数据集的问题（大家一起造的数据集）
1080ti上跑了20分钟，具体step不记得了。

**Comment by HwJhx** [comment]
您是说  我跑出来的结果 和您跑出来的比较接近吗？

**Comment by Yishun99** [comment]
对的

**Comment by 1170300504** [comment]
您好，想问一下为什么只跑了3000多个step，程序就停止了，一个epoch没跑完就停了，也没出现报错
